DAYS_OF_WEEK = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
SHIFT_TYPES = ["MORNING", "AFTERNOON", "EVENING"]
MAX_DAYS_PER_EMPLOYEE = 5
MIN_EMPLOYEES_PER_SHIFT = 2

SHIFTS = {} # {MONDAY : {MORNING: [], AFTERNOON: [], EVENING: []}, TUESDAY: ...}

